[package]
name = "p5_pressure"
version = "0.1.0"
edition = "2021"

[dependencies]
bme280 = "0.5.1"
embedded-hal = "1.0.0"
panic-halt = "1.0.0"
rp235x-hal = { version = "0.3.0", features = [
    "critical-section-impl",
    "defmt",
] }
usb-device = "0.3.2"
usbd-serial = "0.2.2"
